OI-1078 Add Edge support to IDE
oxygenhq/oxygen-ide pull request #220
Opened 2020-12-03 07:36 UTC by savkaoleg

2020-12-04 14:09 UTC, romovs requested changes

2020-12-07 10:55 UTC, savkaoleg commented on app/main/services/SeleniumService/edgedriver-versions.json
> +{
done

2020-12-07 10:55 UTC, savkaoleg commented on app/main/services/SeleniumService/index.js
> +            // try getting the version from a local version map file
done

2020-12-07 10:55 UTC, savkaoleg commented on app/main/services/SeleniumService/index.js
> +                const cp = spawn('taskkill', ['/IM', 'msedge.exe', '/F']);
done

2020-12-07 10:55 UTC, savkaoleg commented on app/main/services/SeleniumService/index.js
> +                const cp = spawn('killall', ['msedge']);
done

2020-12-07 10:56 UTC, savkaoleg commented on app/renderer/components/dialogs/ChromeDriverDownloadingFailedDialog.js
> +                    <p>{`Place the ChromeDriver executable directly into ${path} with name: chromedriver-{versionname} folder`}</p>
done

2020-12-07 10:56 UTC, savkaoleg commented on app/renderer/components/dialogs/EdgeDriverDownloadingFailedDialog.js
> +                    <p>{`Place the ChromeDriver executable directly into ${path} with name: edgedriver-{versionname} folder`}</p>
done

2020-12-07 10:56 UTC, savkaoleg commented on package.json
> +    "extract-zip": "^2.0.1",
done

2020-12-08 08:43 UTC, merged